project:
  type: website
  render:
    - "index.qmd"
  resources:
    - "text-mining.html"
    - "text-mining_files/"
    - "text-modeling.html"
    - "text-modeling_files/"

website:
  title: "today"
  navbar:
    left:
      - href: index.qmd

format: html

theme:
  - cosmo
  - website-styles.scss
